### PR TITLE
Fix compilation with GCC 10 or -fno-common

### PR DESCRIPTION
**Pull request by andrey-utkin**
See https://bugs.gentoo.org/707418

### CODE REVIEW

**Comment by andrey-utkin** [comment]
A new release afterwards would be much appreciated.

**Comment by McKael** [comment]
Thanks Andrey.

I'll probably reimport your patches to the other repository since the Github repo is a mirror, so they will get there but different commit IDs.

**Comment by andrey-utkin** [comment]
Thanks @McKael .
Any news?

**Comment by McKael** [comment]
I've merged the patches upstream (so the hashes don't match and I'll close this PR!).

Thanks again -- and I apologize for the delay...

**Comment by andrey-utkin** [comment]
Issue a release, please!

**Comment by McKael** [comment]
> Issue a release, please!

@andrey-utkin Done (finally), 1.1.1 is out.

**Pull request closed without merging**
